name: 'xatu'
version: '1.0.0'
config-version: 2

profile: 'dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring tests
# Full documentation: https://docs.getdbt.com/reference/test-configs
# tests:
#   clickhouse:

# Configureing seeds
# Full documentation: https://docs.getdbt.com/reference/seed-configs
# seeds:
#   clickhouse:

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  xatu:
    staging:
      beacon_api:
        +materialized: view

vars:
  replicated_merge_tree_engine_template: >
    ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}/{uuid}', '{replica}')
  replicated_replacing_merge_tree_engine_template: >
    ReplicatedReplacingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}/{uuid}', '{replica}')
