dbt:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      schema: dbt
      verify: False
      cluster: '{cluster}'
      cluster_mode: True
      local_suffix: '_local'
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '8123') | int }}"
      secure: "{{ (env_var('DBT_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('DBT_USER', 'default') }}"
      password: "{{ env_var('DBT_PASSWORD', '') }}"
      threads: 4
