dbt:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      schema: dbt
      verify: False
      cluster: '{cluster}'
      cluster_mode: True
      local_suffix: '_local'
      host: "{{ env_var('DBT_HOST') }}"
      port: 443
      secure: True
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      threads: 4
