name: vet
on:
  pull_request:

jobs:
  sqlfluff:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "2.1.2"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: '${{ github.workspace }}/models'
          extra_requirements_txt: '${{ github.workspace }}/requirements.txt'
        env:
          DBT_HOST: ${{ secrets.STAGING_HOST }}
          DBT_USER: ${{ secrets.STAGING_USER }}
          DBT_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
          DBT_PORT: 443
          DBT_SECURE: True
      - name: 'Show outputs'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
