name: vet
on:
  pull_request:

jobs:
  sqlfluff:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: sqlfluff lint .
        env:
          DBT_HOST: ${{ secrets.STAGING_HOST }}
          DBT_PORT: ${{ secrets.STAGING_PORT }}
          DBT_USER: ${{ secrets.STAGING_USER }}
          DBT_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
          DBT_SECURE: ${{ secrets.STAGING_SECURE }}
